name: Deploy Apache Site

on:
  push:
    branches:
      - master   # or main (check your branch)

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to Apache folder
        run: |
          sudo cp -r * /var/www/html/
